version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint fmt
      - golangci-lint --color=always run
    desc: Run golangci-lint on the codebase

  test:
    cmds:
      - go test --count=1 -v -coverprofile cover.out ./...
      - go tool cover -html cover.out -o cover.html
      - go tool cover -func cover.out
      - rm cover.out
    desc: Run tests with coverage
    ignore_error: true

  vuln:
    cmds:
      - govulncheck -show=color -test ./...
    desc: Run Go vulnerability checker
    